# Advanced configuration file for ResourcePackCdn plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

# The base url of the resource pack cdn
base_url: "https://cdn.example.com/"

# The directory where the resource packs are stored
base_dir: "./resource_packs"

# Whether to remove the extension from the resource pack file name
remove_extension: false

